//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power_Control_Panel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power_Control_Panel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Configuration&gt;
        ///	&lt;Profiles&gt;
        ///		&lt;Profile Name=&quot;&quot;&gt;
        ///			&lt;Offline&gt;
        ///				
        ///			&lt;/Offline&gt;
        ///			&lt;Online&gt;
        ///				
        ///				
        ///			&lt;/Online&gt;
        ///		&lt;/Profile&gt;
        ///		
        ///	&lt;/Profiles&gt;
        ///
        ///	&lt;Applications&gt;
        ///		&lt;App DisplayName=&quot;OSFE&quot; Exe=&quot;OSFE.exe&quot; Path=&quot;&quot; AppType=&quot;Game&quot; GameType=&quot;Steam&quot; Image=&quot;&quot; Profile=&quot;&quot; Order=&quot;&quot;/&gt;
        ///		&lt;App DisplayName=&quot;VS2022&quot; Exe=&quot;Visualstudio.exe&quot; Path=&quot;&quot; AppType=&quot;App&quot; GameType=&quot;&quot; Image=&quot;&quot; Profile=&quot;&quot; Order=&quot;&quot;/&gt;
        ///	&lt;/Applications&gt;
        ///	&lt;ApplicationTemplae&gt;
        ///		&lt;App DisplayName=&quot;&quot; Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
    }
}
